### ISSUE TITLE
Permissions issue when building nylon

### ISSUE THREAD

**Issue by kaizushi** [ngocbd/nylon#1]
I cloned the Git repo to my system and I then tried building it. 

When I ran `configure` ...
```
# ./configure
-bash: ./configure: Permission denied
```
So I made it executable and it ran...
`# chmod +x configure`

But now I can't run make because of more permission issues...

```
# make
cd . && /root/nylon/missing aclocal-1.4
/bin/sh: 1: /root/nylon/missing: Permission denied
make: *** [Makefile:105: aclocal.m4] Error 126

```

**Comment by ngocbd** [comment]
You can fix by chmod +x missing .
I will make changes in next commit , thanks .
